server:
  port: 8181
  boss:
    thread:
      count: 2
  worker:
    thread:
      count: 2
  so:
    keepalive: true
    backlog: 100
topic:
  partitions: 3
  replicas: 1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatDB
    driver-class-name: org.postgresql.Driver
    username: admin
    password: P@ssw0rd
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  main:
    allow-circular-references: true
  kafka:
    topic: kafnetty
    group-id: kafnetty-1
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'org.kafnetty.dto'
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
        kafka:
          listener:
            org.springframework.kafka.listener.KafkaMessageListenerContainer: error
      kafnetty: debug
topics:
  retry: 'kafnetty.RETRY'
  dlt: 'kafnetty.DLT'