server:
  port: 8181
  web-socket-path: "/websocket"
  static-path: "/static"
  chat-path: "/chat.html"
  boss:
    thread:
      count: 2
  worker:
    thread:
      count: 2
  so:
    keepalive: true
    backlog: 100
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatDB
    driver-class-name: org.postgresql.Driver
    username: admin
    password: P@ssw0rd
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  main:
    allow-circular-references: true
  kafka:
    topic:
      name: KAFNETTY
    group-id: kafnetty-1
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'org.kafnetty.dto.kafka'
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error