server:
  port: 8182
  web-socket-path: "/websocket"
  static-path: "/static"
  chat-path: "/chat.html"
  cluster-id: "kafnetty-2"
  kafka:
    message-topic: "kafnetty-messages"
    room-topic: "kafnetty-rooms"
    client-topic: "kafnetty-clients"
    servers: "localhost:9092"
  boss:
    thread:
      count: 2
  worker:
    thread:
      count: 2
  so:
    keepalive: true
    backlog: 100
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatDB2
    driver-class-name: org.postgresql.Driver
    username: admin
    password: P@ssw0rd
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  main:
    allow-circular-references: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR